question_titles <- readRDS("data\\metadata\\question_titles.Rds")

local_authorities <- c("Scotland",
                           "Aberdeen City",
                           "Aberdeenshire",
                           "Angus",
                           "Argyll & Bute",
                           "Clackmannanshire",
                           "Dumfries & Galloway",
                           "Dundee City",
                           "East Ayrshire",
                           "East Dunbartonshire",
                           "East Lothian",
                           "East Renfrewshire",
                           "Edinburgh, City of",
                           "Falkirk",
                           "Fife",
                           "Glasgow City",
                           "Highland",
                           "Inverclyde",
                           "Midlothian",
                           "Moray",
                           "Na h-Eileanan Siar",
                           "North Ayrshire",
                           "North Lanarkshire",
                           "Orkney Islands",
                           "Perth & Kinross",
                           "Renfrewshire",
                           "Scottish Borders",
                           "Shetland Islands",
                           "South Ayrshire",
                           "South Lanarkshire",
                           "Stirling",
                           "West Dunbartonshire",
                           "West Lothian")

select_list_chapters <- c("Ch. 2: The Composition and Characteristics of Households in Scotland" = "The Composition and Characteristics of Households in Scotland",
"Ch. 3: Housing" = "Housing",
"Ch. 4: Neighbourhoods and Communities" = "Neighbourhoods and Communities",
"Ch. 5: Economic Activity" = "Economic Activity",
"Ch. 6: Finance" = "Finance",
"Ch. 7: Internet" = "Internet",
"Ch. 8: Physical Activity and Sport" = "Physical Activity and Sport",
"Ch. 9: Local Services" = "Local Services",
"Ch. 10: Environment" = "Environment",
"Ch. 11: Volunteering" = "Volunteering",
"Ch. 12: Culture and Heritage" = "Culture and Heritage")

select_list_questions_chapter_2 <- c("Table 2.1: Age of all household members by year" = "Table 2.1",
"Table 2.2: Gender of all household members by year" = "Table 2.2",
"Table 2.3: All household members with a long-term physical or mental health condition by year" = "Table 2.3",
"Figure 2.1: Age of adults by year" = "Figure 2.1",
"Figure 2.2: Gender of adults by year" = "Figure 2.2",
"Table 2.4, Figure 2.3: Adults with a long-term physical or mental health condition by year" = "Table 2.4, Figure 2.3",
"Table 2.5: Ethnicity of adults by year" = "Table 2.5",
"Table 2.6: Economic status of all adults aged 16-64" = "Table 2.6",
"Figure 2.4: Economic status of adults by year - selected groups" = "Figure 2.4",
"Table 2.7: Sexual orientation of adults by year" = "Table 2.7",
"Figure 2.5: Religious belonging of adults by year" = "Figure 2.5",
"Table 2.8: Marital status of adults by year" = "Table 2.8",
"Table 2.9: Current marital status of adults by age" = "Table 2.9",
"Table 2.10: Age of adults by marital status" = "Table 2.10",
"Table 2.11: Household type of households by year" = "Table 2.11",
"Table 2.12: Households with children by year" = "Table 2.12",
"Table 2.13: Property type of households by year" = "Table 2.13",
"Table 2.14: Tenure of households by year" = "Table 2.14",
"Table 2.15: Scottish Index of Multiple Deprivation of households by year" = "Table 2.15",
"Table 2.16: Urban rural split of households by year" = "Table 2.16",
"Table 2.17: Household income of households by year" = "Table 2.17")

select_list_questions_chapter_3 <- c("Figure 3.1: Tenure of households by year" = "Figure 3.1",
"Table 3.1: Tenure of household by year" = "Table 3.1",
"Table 3.1b: Households by tenure and year" = "Table 3.1b",
"Figure 3.2: Households by age of highest income householder" = "Figure 3.2",
"Figure 3.3: Tenure of households by year (HIH aged 16 to 34)" = "Figure 3.3",
"Figure 3.4: Tenure of households by year (HIH aged 35 to 59)" = "Figure 3.4",
"Figure 3.5: Tenure of households by year (HIH aged 60 plus)" = "Figure 3.5",
"Table 3.2a: Housing characteristics by tenure - Dwelling type" = "Table 3.2a",
"Table 3.2b: Housing characteristics by tenure - SIMD" = "Table 3.2b",
"Table 3.2c: Housing characteristics by tenure - Urban / Rural Classification" = "Table 3.2c",
"Table 3.2d: Housing characteristics by tenure - Number of bedrooms" = "Table 3.2d",
"Table 3.3a: Household characteristics by tenure - Number of people in household" = "Table 3.3a",
"Table 3.3b: Household characteristics by tenure - Household composition" = "Table 3.3b",
"Table 3.3c: Household characteristics by tenure - Age" = "Table 3.3c",
"Table 3.3d: Household characteristics by tenure - Number of cars" = "Table 3.3d",
"Table 3.3e: Household characteristics by tenure - Net household income" = "Table 3.3e",
"Table 3.3f: How well household is managing financially" = "Table 3.3f",
"Table 3.4a: Adult characteristics by tenure - Ethnicity" = "Table 3.4a",
"Table 3.4b: Adult characteristics by tenure - Economic situation" = "Table 3.4b",
"Table 3.4c: Adult characteristics by tenure - Length of time at current address" = "Table 3.4c",
"Table 3.4d: Adult characteristics by tenure - Tenure of previous address" = "Table 3.4d",
"Table 3.4e: Adult characteristics by tenure - Whether the change of address was to join an existing family/household, or to occupy the entire property" = "Table 3.4e",
"Table 3.5a: Views on housing aspirations, by tenure - Reasons for moving to the area" = "Table 3.5a",
"Table 3.5b: Views on housing aspirations, by tenure - When the household expects to move" = "Table 3.5b",
"Table 3.6a: Views on housing aspirations, by tenure - Accommodation householder would like to live in" = "Table 3.6a",
"Table 3.6b: Compared to current accommodation, the size of property householder would most like to live in" = "Table 3.6b",
"Table 3.6c: Barriers to moving to the accommodation the householder would most like to live i" = "Table 3.6c",
"Figure 3.6: Percentage of households very or fairly satisfied with housing" = "Figure 3.6",
"Table 3.7a: Views on neighbourhood and housing aspirations, by tenure - Rating of neighbourhood as a place to live" = "Table 3.7a",
"Table 3.7b: Views on neighbourhoods and housing aspirations, by tenure - Strength of belonging to immediate neighbourhood" = "Table 3.7b",
"Table 3.7c: Views on neighbourhoods and housing aspirations, by tenure - Housing satisfaction" = "Table 3.7c",
"Table 3.8: Households renting privately – information on landlord / letting agents and deposits" = "Table 3.8",
"Table 3.9a: Limiting activities by tenure - Household has someone with a long term physical/mental health condition/illness*" = "Table 3.9a",
"Table 3.9b: Limiting activities by tenure - What about the home limits activities that can be done" = "Table 3.9b",
"Table 3.9c: Limiting activities by tenure - Whether the home requires adaptations to  make it easier to go about daily activities" = "Table 3.9c",
"Table 3.10a: Housing adaptations and support - Home adaptations that are already in place" = "Table 3.10a",
"Table 3.10b: Housing adaptations and support - Services that household members currently receive" = "Table 3.10b",
"Table 3.11a: Households on a housing list by tenure - Whether household is on a housing list" = "Table 3.11a",
"Table 3.11b: Households on a housing list by tenure - If not on a housing list, whether household has applied for social housing under a choice-based letting scheme, or similar, in the last year" = "Table 3.11b",
"Table 3.11c: Households on a housing list by tenure - The number of housing lists that households are on (households on a list)" = "Table 3.11c",
"Table 3.11d: Households on a housing list by tenure - How long the household has been on a housing list (households on a list)" = "Table 3.11d",
"Table 3.11e: Households on a housing list by tenure - The main reason for household being on a housing list (households on a list)" = "Table 3.11e",
"Table 3.12: Adults on housing lists" = "Table 3.12",
"Table 3.13: Households on housing lists" = "Table 3.13",
"Table 3.14: Urban Rural Location of Private Rented Households, by year" = "Table 3.14",
"Table 3.15: Age of Highest Income Householder in Private Rented Households, by year" = "Table 3.15",
"Table 3.16: Household Composition of Private Rented Households, by year" = "Table 3.16",
"Table 3.17: Economic situation of Adults in Private Rented Households, by year" = "Table 3.17",
"Table 3.18: Length of Time at address in private rented households, by year" = "Table 3.18")

select_list_questions_chapter_4 <- c("Table 4.1: Rating of neighbourhood as a place to live by year" = "Table 4.1",
"Table 4.2: Rating of neighbourhood as a place to live by Urban Rural Classification" = "Table 4.2",
"Figure 4.1: Rating of neighbourhood as a place to live by Scottish Index of Multiple Deprivation" = "Figure 4.1",
"Figure 4.2a: Rating of neighbourhood as a place to live by Scottish Index of Multiple Deprivation - 20% most deprived areas" = "Figure 4.2a",
"Figure 4.2b: Rating of neighbourhood as a place to live by Scottish Index of Multiple Deprivation - 20% least deprived areas" = "Figure 4.2b",
"Table 4.3: Percentage of people agreeing with statements about their neighbourhood strengths" = "Table 4.3",
"Table 4.4: Percentage of people agreeing with statements about their neighbourhood strengths by age" = "Table 4.4",
"Table 4.5: Percentage of people agreeing with statements about their neighbourhood strengths by Urban Rural Classification" = "Table 4.5",
"Table 4.6: Percentage of people agreeing with statements about their neighbourhood strengths by tenure" = "Table 4.6",
"Table 4.7: Strength of feeling of belonging to community by gender, age, ethnicity and Scottish Index of Multiple Deprivation" = "Table 4.7",
"Table 4.8a: Percentage of people agreeing with statements about their involvement with other people in the neighbourhood" = "Table 4.8a",
"Table 4.8b: Percentage of people agreeing with statements about their involvement with other people in the neighbourhood" = "Table 4.8b",
"Table 4.9: How often people meet socially with friends, relatives, neighbours or work colleagues by age and gender" = "Table 4.9",
"Table 4.10: How often people meet socially with friends, relatives, neighbours or work colleagues by Urban-Rural Classification and SIMD" = "Table 4.10",
"Table 4.11: How often people meet socially with friends, relatives, neighbours or work colleagues by long-term physical or mental health condition" = "Table 4.11",
"Table 4.12: How often people have felt lonely within the last week by age" = "Table 4.12",
"Table 4.13: How often people have felt lonely within the last week by SIMD" = "Table 4.13",
"Table 4.14: How often people have felt lonely within the last week by Urban-Rural Classification" = "Table 4.14",
"Table 4.15: How often people have felt lonely within the last week by long-term physical or mental health condition" = "Table 4.15",
"Table 4.16: How often people have felt lonely within the last week by household type" = "Table 4.16",
"Table 4.17: Percentage of people saying a problem is very/fairly common in their neighbourhood" = "Table 4.17",
"Table 4.18: Percentage of people saying a problem is very/fairly common in their neighbourhood by Scottish Index of Multiple Deprivation" = "Table 4.18",
"Table 4.19: Percentage of people saying a problem is very/fairly common in their neighbourhood by tenure of household" = "Table 4.19",
"Table 4.20: Percentage of people saying a problem is very/fairly common in their neighbourhood by age of respondent" = "Table 4.20",
"Table 4.21: Percentage of people saying a problem is very/fairly common in their neighbourhood by Urban Rural classification" = "Table 4.21",
"Figure 4.3: Perceptions and experience of neighbourhood problems" = "Figure 4.3",
"Table 4.22: Experience of neighbourhood problems by Scottish Index of Multiple Deprivation" = "Table 4.22",
"Table 4.23: Experience of neighbourhood problems by tenure of household" = "Table 4.23",
"Table 4.24: Experience of neighbourhood problems by Urban Rural Classification" = "Table 4.24",
"Table 4.25: Experiences of discrimination and harassment by gender, age and deprivation" = "Table 4.25",
"Table 4.26: Experiences of discrimination and harassment by sexual orientation, ethnicity, religion, and long term physical/mental health condition" = "Table 4.26",
"Table 4.27: Reasons for discrimination and harassment" = "Table 4.27",
"Table 4.28: Activity undertaken to prepare for events like severe weather or flooding" = "Table 4.28",
"Table 4.29: Availability of emergency response items in household by tenure of household and Scottish Index of Multiple Deprivation" = "Table 4.29")

select_list_questions_chapter_5 <- c("Table 5.1, Figure 5.1: Highest level of qualifications held by adults aged 16 and over by year, 2007-2018" = "Table 5.1, Figure 5.1",
"Table 5.2: Highest level of qualification held by gender and age of adults aged 16 and over" = "Table 5.2",
"Table 5.3, Figure 5.2: Highest level of qualification held by adults aged 16-64 by net annual household income" = "Table 5.3, Figure 5.2",
"Figure 5.3: Current economic situation of adults aged 16 and over" = "Figure 5.3",
"Figure 5.4: Adults aged 16 and over in work over time, 1999-2018" = "Figure 5.4",
"Figure 5.5: Current economic situation of adults aged 16-64 over time, 1999-2018" = "Figure 5.5",
"Figure 5.6: Current economic situation of adults aged 16-64 by gender" = "Figure 5.6",
"Table 5.4: Current economic situation of adults aged 16-64 by highest level of qualification" = "Table 5.4",
"Table 5.5: Current economic situation of adults aged 16-64 by long-standing limiting illness, health problem or disability" = "Table 5.5",
"Figure 5.7: Number of adults aged 16 or over in paid employment by Scottish Index of Multiple Deprivation" = "Figure 5.7",
"Figure 5.8: Current economic situation of women aged 16-64 by the presence of children in the household" = "Figure 5.8")

select_list_questions_chapter_6 <- c("Figure 6.1: How households are managing financially by year" = "Figure 6.1",
"Figure 6.2: How the household is managing financially by net annual household income" = "Figure 6.2",
"Figure 6.3: How the household is managing financially by household type" = "Figure 6.3",
"Figure 6.4: How the household is managing financially by tenure of household" = "Figure 6.4",
"Table 6.1: How the household is managing financially by income sources" = "Table 6.1",
"Table 6.2: How the household is managing financially this year by gender and age of highest income householder" = "Table 6.2",
"Figure 6.5: How households were managing financially by the Scottish Index of Multiple Deprivation" = "Figure 6.5",
"Figure 6.6: Households who manage well financially by deprivation over time" = "Figure 6.6")

select_list_questions_chapter_7 <- c("Figure 7.1: Households with home internet access by year" = "Figure 7.1",
"Figure 7.2: Households with home internet access by net annual household income" = "Figure 7.2",
"Figure 7.3: Households with home internet access by year and net annual household income" = "Figure 7.3",
"Figure 7.4: Households with home internet access by SIMD and year" = "Figure 7.4",
"Figure 7.5: Households with home internet access by tenure" = "Figure 7.5",
"Figure 7.6: Households with home internet access by Urban Rural classification" = "Figure 7.6",
"Figure 7.7: Use of internet over time and by age" = "Figure 7.7",
"Figure 7.8: Use of internet by age" = "Figure 7.8",
"Table 7.1: Use of the internet by whether has a long-standing limiting illness, health problem or disability and age" = "Table 7.1",
"Figure 7.9: Use of the internet by net annual household income" = "Figure 7.9",
"Figure 7.10: Use of the internet by year and net annual household income" = "Figure 7.10",
"Figure 7.11: Use of the internet by area deprivation level" = "Figure 7.11",
"Figure 7.12: Use of internet by tenure" = "Figure 7.12",
"Table 7.2: Where adults who use the internet access it for personal use" = "Table 7.2",
"Table 7.3: Smart appliances in the house by area deprivation" = "Table 7.3",
"Table 7.4: Which methods are used to access the internet for personal use by age" = "Table 7.4",
"Table 7.5: Reasons for using the internet by tenure" = "Table 7.5",
"Table 7.6: Percentage of confident users by tenure" = "Table 7.6",
"Table 7.7: Reasons that could convince people, who don't use the internet for personal use, to online" = "Table 7.7",
"Table 7.8: Use of public services on the internet in the past 12 months (internet users)" = "Table 7.8",
"Table 7.9: Satisfaction with quality of public service websites" = "Table 7.9",
"Table 7.10: Online security measures by age and deprivation" = "Table 7.10",
"Table 7.11: Impact of security concerns on internet use by age and physical or mental health condition" = "Table 7.11")

select_list_questions_chapter_8 <- c("Table 8.1, Figure 8.1, Figure 8.2: Trends in participation in physical activity and sport in the last four weeks, 2007 to 2018" = "Table 8.1, Figure 8.1, Figure 8.2",
"Figure 8.3: Trends in frequency of participation by adults who took part in physical activity and sport in the previous four weeks" = "Figure 8.3",
"Table 8.2: Participation in physical activity and sport in the past four weeks by gender and age" = "Table 8.2",
"Figure 8.4: Trends in participation in physical activity and sport (including walking) in the last four weeks by age" = "Figure 8.4",
"Figure 8.5: Trends in participation in any physical activity and sport (excluding walking) in the last four weeks by age" = "Figure 8.5",
"Figure 8.6: Trends in participation in recreational walking in the last four weeks by age" = "Figure 8.6",
"Figure 8.7: Participation in physical activity and sport in the past four weeks by highest level of qualification" = "Figure 8.7",
"Figure 8.8: Participation in physical activity and sport in the past four weeks by Scottish Index of Multiple Deprivation" = "Figure 8.8",
"Table 8.3: Participation in different types of physical activity and sport in the last four weeks by Scottish Index of Multiple Deprivation" = "Table 8.3",
"Figure 8.9: Participation in physical activity and sport (including walking) in the last four weeks over time by Scottish Index of Multiple Deprivation" = "Figure 8.9",
"Figure 8.10: Participation in physical activity and sport (excluding walking) in the last four weeks over time by Scottish Index of Multiple Deprivation" = "Figure 8.10",
"Figure 8.11: Participation in walking (at least 30 minutes) in the last four weeks over time by Scottish Index of Multiple Deprivation" = "Figure 8.11",
"Figure 8.12: Participation of none of these in the last four weeks over time by Scottish Index of Multiple Deprivation" = "Figure 8.12",
"Figure 8.13: Participation in physical activity and sport in the last four weeks, by long-term physical/mental health condition" = "Figure 8.13",
"Table 8.4: Satisfaction with local authority sport and leisure facilities" = "Table 8.4",
"Table 8.5: Satisfaction with local authority cultural and sport facilities (service users in the past 12 months only)" = "Table 8.5")

select_list_questions_chapter_9 <- c("Figure 9.1, Table 9.1: Percentage of people very or fairly satisfied with the quality of public services delivered (local health services, local schools and public transport) by year" = "Figure 9.1, Table 9.1",
"Table 9.2: Percentage of people very or fairly satisfied with the quality of public services delivered (local health services, local schools and public transport) by year" = "Table 9.2",
"Table 9.3: Percentage of people very or fairly satisfied with the quality of public services delivered (local health services, local schools and public transport) by Urban Rural Classification" = "Table 9.3",
"Table 9.4: Percentage of people very or fairly satisfied with the quality of public services delivered (local health services, local schools and public transport) by Scottish Index of Multiple Deprivation" = "Table 9.4",
"Table 9.5: Percentage of service users very or fairly satisfied with the quality of public services delivered (local health services, local schools and public transport) by year" = "Table 9.5",
"Figure 9.2: Percentage agreeing with various statements about local authority services and performances" = "Figure 9.2",
"Table 9.6: Percentage of people who agree with the statement 'I can influence decisions affecting my local area' by year" = "Table 9.6",
"Table 9.7: Percentage agreeing with various statements about local council services by year" = "Table 9.7",
"Figure 9.3: Percentage agreeing with various statements about local council services by age" = "Figure 9.3",
"Figure 9.4: Percentage agreeing with various statements about local council services by Scottish Index of Multiple Deprivation (SIMD)" = "Figure 9.4")

select_list_questions_chapter_10 <- c("Table 10.1: Perceptions about climate change as a problem" = "Table 10.1",
"Figure 10.1: Perception about climate change as an 'immediate and urgent problem' by age" = "Figure 10.1",
"Figure 10.2: Percentage of adults perceiving that 'Climate change is an immediate and urgent problem' by educational attainment" = "Figure 10.2",
"Figure 10.3: Percentage of adults perceiving that 'Climate change is an immediate and urgent problem' by area deprivation" = "Figure 10.3",
"Table 10.2: 'It’s not worth me doing things to help the environment if others don’t do the same”" = "Table 10.2",
"Table 10.3: 'I don’t believe my behaviour and everyday lifestyle contribute to climate change'" = "Table 10.3",
"Table 10.4: 'Climate change will only have an impact on other countries, there is no need for me to worry'" = "Table 10.4",
"Table 10.5: 'I understand what actions people like myself should take to help tackle climate change'" = "Table 10.5",
"Table 10.6: Frequency of visits made to the outdoors" = "Table 10.6",
"Table 10.7: Frequency of visits made to the outdoors by Scottish Index of Multiple Deprivation" = "Table 10.7",
"Figure 10.4: Percentage of adults visiting outdoors at least once a week" = "Figure 10.4",
"Table 10.8: Frequency of visits made to the outdoors by urban/rural classification" = "Table 10.8",
"Table 10.9: Frequency of visits made to the outdoors by age group and gender" = "Table 10.9",
"Table 10.10: Frequency of visits made to the outdoors by self perception of health" = "Table 10.10",
"Figure 10.5: Walking distance to nearest useable greenspace" = "Figure 10.5",
"Table 10.11: Walking distance to nearest greenspace by Scottish Index of Multiple Deprivation" = "Table 10.11",
"Figure 10.6: Percentage of adults expressing satisfaction with nearest greenspace" = "Figure 10.6",
"Figure 10.7: Percentage of adults who have not visited nearest greenspace in previous 12 months" = "Figure 10.7",
"Table 10.12: Percentage of people who gave their views on land use in the last 12 months" = "Table 10.12",
"Table 10.13: Percentage of People who gave their views on land use by urban rural classification" = "Table 10.13")

select_list_questions_chapter_11 <- c("Table 11.1: Whether involved in any Volunteering (Formal or Informal) in the last 12 months by gender" = "Table 11.1",
"Table 11.2: Whether provided unpaid help to organisations or groups in the last 12 months by gender" = "Table 11.2",
"Figure 11.1: Whether provided unpaid help to organisations or groups in the last 12 months by gender" = "Figure 11.1",
"Figure 11.2: Percentage providing unpaid help to organisations or groups in the last 12 months by age within gender" = "Figure 11.2",
"Table 11.3: Whether provided unpaid help to organisations or groups in the last 12 months by current economic situation" = "Table 11.3",
"Table 11.4: Whether provided unpaid help to organisations or groups in the last 12 months by net annual household income" = "Table 11.4",
"Figure 11.3: Whether provided unpaid help to organisations or groups in the last 12 months by Scottish Index of Multiple Deprivation" = "Figure 11.3",
"Table 11.5: Whether provided unpaid help to organisations or groups in the last 12 months by Urban/Rural classification" = "Table 11.5",
"Table 11.6: Types of organizations or groups for which adults provided help in the last 12 months by Urban/Rural classification" = "Table 11.6",
"Table 11.7: Types of organisations or groups for which adults provided help in the last 12 months by age and gender" = "Table 11.7",
"Table 11.8: Types of work / unpaid activity adults have undertaken in the last 12 months by age and gender" = "Table 11.8",
"Table 11.9: Frequency of unpaid help to organisations or groups in the last 12 months by age and gender" = "Table 11.9",
"Table 11.10: Total number of hours of unpaid work provided in the past month" = "Table 11.10",
"Table 11.11: Reasons why adults may undertake unpaid help in the future" = "Table 11.11",
"Table 11.12: Whether involved in any Informal Volunteering in the last 12 months by gender" = "Table 11.12",
"Figure 11.4: Whether involved in any Informal Volunteering in the last 12 months by age within gender" = "Figure 11.4",
"Table 11.13: Whether involved in any Informal Volunteering in the last 12 months by current economic status" = "Table 11.13",
"Table 11.14: Whether involved in any Informal Volunteering in the last 12 months by net annual income" = "Table 11.14",
"Figure 11.5: Whether involved in any Informal Volunteering in the last 12 months by Scottish Index of Multiple Deprivation" = "Figure 11.5",
"Table 11.15: Whether involved in any Informal Volunteering in the last 12 months by Urban/Rural classification" = "Table 11.15",
"Table 11.16: Types of Informal Volunteering activity in the last 12 months by gender and age" = "Table 11.16",
"Table 11.17: Frequency of Informal Volunteering in the last 12 months by gender and age" = "Table 11.17",
"Table 11.18: Total number of Informal Volunteering hours in the last 12 months" = "Table 11.18")

select_list_questions_chapter_12 <- c("Figure 12.1: Cultural engagement by adults in the last 12 months by year" = "Figure 12.1",
"Table 12.1: Attendance at any cultural event and visiting place of culture in the last 12 months by year" = "Table 12.1",
"Figure 12.2: Attendance at cultural events and visiting places of culture in the last 12 months in 2018" = "Figure 12.2",
"Table 12.2: Attendance at cultural events and visiting places of culture in the last 12 months by gender" = "Table 12.2",
"Table 12.3: Attendance at cultural events and visiting places of culture in the last 12 months by age" = "Table 12.3",
"Table 12.4, Figure 12.3: Attendance at cultural events and visiting places of culture in the last 12 months by highest qualification level" = "Table 12.4, Figure 12.3",
"Table 12.5, Figure 12.4: Attendance at cultural events and visiting places of culture in the last 12 months by area deprivation" = "Table 12.5, Figure 12.4",
"Table 12.6, Figure 12.5: Attendance at cultural events and visiting places of culture in the last 12 months by net annual household income" = "Table 12.6, Figure 12.5",
"Table 12.7, Figure 12.6: Attendance at cultural events and visiting places of culture in the last 12 months by long term physical/mental health condition" = "Table 12.7, Figure 12.6",
"Table 12.8: Frequency of attending cultural events and visiting places of culture in the last 12 months" = "Table 12.8",
"Table 12.9: Participation in any cultural activity in the last 12 months by year" = "Table 12.9",
"Figure 12.7: Participation in cultural activities in the last 12 months in 2018" = "Figure 12.7",
"Table 12.10: Participation in cultural activities in the last 12 months by gender" = "Table 12.10",
"Table 12.11: Participation in cultural activities in the last 12 months by age" = "Table 12.11",
"Table 12.12, Figure 12.8: Participation in cultural activities in the last 12 months by highest level of qualification" = "Table 12.12, Figure 12.8",
"Table 12.13, Figure 12.9: Participation in cultural events and visiting places of culture in the last 12 months by Scottish Index of Multiple Deprivation" = "Table 12.13, Figure 12.9",
"Table 12.14, Figure 12.10: Participation in cultural events and visiting places of culture in the last 12 months by net annual household income" = "Table 12.14, Figure 12.10",
"Table 12.15, Figure 12.11: Participation in cultural activities in the last 12 months by long term physical/mental health condition physical/mental health condition" = "Table 12.15, Figure 12.11",
"Table 12.16: Frequency of participating in cultural activities in the last 12 months" = "Table 12.16",
"Table 12.17: Satisfaction with local authority culture facilities." = "Table 12.17",
"Table 12.18: Satisfaction with local authority culture facilities; service users in the past year only" = "Table 12.18")

type_0_questions <- question_titles$ID[question_titles$Type == 0]

type_1_questions <- question_titles$ID[question_titles$Type == 1]

type_2_questions <- question_titles$ID[question_titles$Type == 2]

type_3_questions <- question_titles$ID[question_titles$Type == 3]

type_4_questions <- question_titles$ID[question_titles$Type == 4]

